shared:
  blacklist: &blacklist
    - "@eaDir"
    - "*.!sync"
    - ".sync"
    - "*.crdownload"

pipelines:
  - name: ooxx
    glob: "*"
    input: ./local/test/ooxx
    blacklist: *blacklist
    context:
      output: ./local/test/output/ooxx
    process:
      - type: skip_directory
      - type: generate_uuid
        arg: 6
      - type: parse_filename
      - type: lock_acquire
        arg: global
      - type: delay
        arg: 5
      - type: failure
      - type: move
        arg: "{output}/{relative_parent}/{uuid}{suffix}"
      - type: debug_info
      - type: lock_release
        arg: global
    failure:
      - type: lock_release
