pipelines:
  - name: ooxx
    pattern: wtf.*
    input: ./test/ooxx
    context:
      output: ./test/output/ooxx
    process:
      - type: skip_directory
      - type: delay
        arg: "1.0"
      # - type: move
      #   arg: "ooxx/{timestamp}-{md5}.{suffix}"
      - type: debug_info
