pipelines:
  - name: wtf
    re: "wtf(?!\\d).*.txt"
    input: ./test/ooxx
    context:
      output: ./test/output/ooxx
    process:
      - type: debug_info
  - name: ooxx
    glob: "*"
    input: ./test/ooxx
    context:
      output: ./test/output/ooxx
    process:
      - type: skip_directory
      - type: parse_filename
      - type: move
        arg: "{output}/{relative_parent}/{timestamp:0.0f}{suffix}"
      - type: debug_info