shared:
  blacklist: &blacklist
    - "@eaDir"
    - "*.!sync"
    - ".sync"
    - "*.crdownload"

pipelines:
  - name: wtf
    re: "wtf(?!\\d).*.txt"
    blacklist: *blacklist
    input: ./test/ooxx
    context:
      output: ./test/output/ooxx
    process:
      - type: debug_info
  - name: ooxx
    glob: "*"
    input: ./test/ooxx
    blacklist: *blacklist
    context:
      output: ./test/output/ooxx
    process:
      - type: skip_directory
      - type: parse_filename
      - type: move
        arg: "{output}/{relative_parent}/{timestamp:0.0f}{suffix}"
      - type: debug_info
